/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BuyerRouteImport } from './routes/buyer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as BuyerIndexRouteImport } from './routes/buyer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorProductsRouteImport } from './routes/vendor.products'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorInventoryRouteImport } from './routes/vendor.inventory'
import { Route as VendorAnalyticsRouteImport } from './routes/vendor.analytics'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as BuyerOrdersRouteImport } from './routes/buyer.orders'
import { Route as BuyerEnquiriesRouteImport } from './routes/buyer.enquiries'
import { Route as BuyerCatalogueRouteImport } from './routes/buyer.catalogue'
import { Route as BuyerAccountRouteImport } from './routes/buyer.account'
import { Route as AdminWarehouseRouteImport } from './routes/admin.warehouse'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminBuyersRouteImport } from './routes/admin.buyers'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRoute = BuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const BuyerIndexRoute = BuyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuyerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorInventoryRoute = VendorInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => VendorRoute,
} as any)
const VendorAnalyticsRoute = VendorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => VendorRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerOrdersRoute = BuyerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerEnquiriesRoute = BuyerEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerCatalogueRoute = BuyerCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerAccountRoute = BuyerAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => BuyerRoute,
} as any)
const AdminWarehouseRoute = AdminWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuyersRoute = AdminBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/buyer': typeof BuyerRouteWithChildren
  '/cart': typeof CartRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/vendor': typeof VendorRouteWithChildren
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/warehouse': typeof AdminWarehouseRoute
  '/buyer/account': typeof BuyerAccountRoute
  '/buyer/catalogue': typeof BuyerCatalogueRoute
  '/buyer/enquiries': typeof BuyerEnquiriesRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/product/$id': typeof ProductIdRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/inventory': typeof VendorInventoryRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/admin/': typeof AdminIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/warehouse': typeof AdminWarehouseRoute
  '/buyer/account': typeof BuyerAccountRoute
  '/buyer/catalogue': typeof BuyerCatalogueRoute
  '/buyer/enquiries': typeof BuyerEnquiriesRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/product/$id': typeof ProductIdRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/inventory': typeof VendorInventoryRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/admin': typeof AdminIndexRoute
  '/buyer': typeof BuyerIndexRoute
  '/vendor': typeof VendorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/buyer': typeof BuyerRouteWithChildren
  '/cart': typeof CartRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/vendor': typeof VendorRouteWithChildren
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/warehouse': typeof AdminWarehouseRoute
  '/buyer/account': typeof BuyerAccountRoute
  '/buyer/catalogue': typeof BuyerCatalogueRoute
  '/buyer/enquiries': typeof BuyerEnquiriesRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/product/$id': typeof ProductIdRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/inventory': typeof VendorInventoryRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/admin/': typeof AdminIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/buyer'
    | '/cart'
    | '/catalogue'
    | '/contact'
    | '/login'
    | '/notifications'
    | '/orders'
    | '/vendor'
    | '/admin/buyers'
    | '/admin/enquiries'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/staff'
    | '/admin/users'
    | '/admin/vendors'
    | '/admin/warehouse'
    | '/buyer/account'
    | '/buyer/catalogue'
    | '/buyer/enquiries'
    | '/buyer/orders'
    | '/product/$id'
    | '/vendor/analytics'
    | '/vendor/inventory'
    | '/vendor/orders'
    | '/vendor/products'
    | '/admin/'
    | '/buyer/'
    | '/vendor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/catalogue'
    | '/contact'
    | '/login'
    | '/notifications'
    | '/orders'
    | '/admin/buyers'
    | '/admin/enquiries'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/staff'
    | '/admin/users'
    | '/admin/vendors'
    | '/admin/warehouse'
    | '/buyer/account'
    | '/buyer/catalogue'
    | '/buyer/enquiries'
    | '/buyer/orders'
    | '/product/$id'
    | '/vendor/analytics'
    | '/vendor/inventory'
    | '/vendor/orders'
    | '/vendor/products'
    | '/admin'
    | '/buyer'
    | '/vendor'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/buyer'
    | '/cart'
    | '/catalogue'
    | '/contact'
    | '/login'
    | '/notifications'
    | '/orders'
    | '/vendor'
    | '/admin/buyers'
    | '/admin/enquiries'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/staff'
    | '/admin/users'
    | '/admin/vendors'
    | '/admin/warehouse'
    | '/buyer/account'
    | '/buyer/catalogue'
    | '/buyer/enquiries'
    | '/buyer/orders'
    | '/product/$id'
    | '/vendor/analytics'
    | '/vendor/inventory'
    | '/vendor/orders'
    | '/vendor/products'
    | '/admin/'
    | '/buyer/'
    | '/vendor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuyerRoute: typeof BuyerRouteWithChildren
  CartRoute: typeof CartRoute
  CatalogueRoute: typeof CatalogueRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  VendorRoute: typeof VendorRouteWithChildren
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/buyer/': {
      id: '/buyer/'
      path: '/'
      fullPath: '/buyer/'
      preLoaderRoute: typeof BuyerIndexRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/inventory': {
      id: '/vendor/inventory'
      path: '/inventory'
      fullPath: '/vendor/inventory'
      preLoaderRoute: typeof VendorInventoryRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/analytics': {
      id: '/vendor/analytics'
      path: '/analytics'
      fullPath: '/vendor/analytics'
      preLoaderRoute: typeof VendorAnalyticsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/orders': {
      id: '/buyer/orders'
      path: '/orders'
      fullPath: '/buyer/orders'
      preLoaderRoute: typeof BuyerOrdersRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/enquiries': {
      id: '/buyer/enquiries'
      path: '/enquiries'
      fullPath: '/buyer/enquiries'
      preLoaderRoute: typeof BuyerEnquiriesRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/catalogue': {
      id: '/buyer/catalogue'
      path: '/catalogue'
      fullPath: '/buyer/catalogue'
      preLoaderRoute: typeof BuyerCatalogueRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/account': {
      id: '/buyer/account'
      path: '/account'
      fullPath: '/buyer/account'
      preLoaderRoute: typeof BuyerAccountRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/admin/warehouse': {
      id: '/admin/warehouse'
      path: '/warehouse'
      fullPath: '/admin/warehouse'
      preLoaderRoute: typeof AdminWarehouseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buyers': {
      id: '/admin/buyers'
      path: '/buyers'
      fullPath: '/admin/buyers'
      preLoaderRoute: typeof AdminBuyersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBuyersRoute: typeof AdminBuyersRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminWarehouseRoute: typeof AdminWarehouseRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBuyersRoute: AdminBuyersRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminWarehouseRoute: AdminWarehouseRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BuyerRouteChildren {
  BuyerAccountRoute: typeof BuyerAccountRoute
  BuyerCatalogueRoute: typeof BuyerCatalogueRoute
  BuyerEnquiriesRoute: typeof BuyerEnquiriesRoute
  BuyerOrdersRoute: typeof BuyerOrdersRoute
  BuyerIndexRoute: typeof BuyerIndexRoute
}

const BuyerRouteChildren: BuyerRouteChildren = {
  BuyerAccountRoute: BuyerAccountRoute,
  BuyerCatalogueRoute: BuyerCatalogueRoute,
  BuyerEnquiriesRoute: BuyerEnquiriesRoute,
  BuyerOrdersRoute: BuyerOrdersRoute,
  BuyerIndexRoute: BuyerIndexRoute,
}

const BuyerRouteWithChildren = BuyerRoute._addFileChildren(BuyerRouteChildren)

interface VendorRouteChildren {
  VendorAnalyticsRoute: typeof VendorAnalyticsRoute
  VendorInventoryRoute: typeof VendorInventoryRoute
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorProductsRoute: typeof VendorProductsRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorAnalyticsRoute: VendorAnalyticsRoute,
  VendorInventoryRoute: VendorInventoryRoute,
  VendorOrdersRoute: VendorOrdersRoute,
  VendorProductsRoute: VendorProductsRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BuyerRoute: BuyerRouteWithChildren,
  CartRoute: CartRoute,
  CatalogueRoute: CatalogueRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  VendorRoute: VendorRouteWithChildren,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
